#!/bin/zsh

# Aliases
alias zshrc='$EDITOR ~/.zshrc'
alias ohmyzsh='$EDITOR ~/.oh-my-zsh'
alias cat='bat'
alias ll='ls -alFh'
alias search='grep -i -E'
alias hs='history | search'

# Kubernetes
alias k='kubectl'
alias kaf='kubectl apply -f'
alias kdf='kubectl diff -f'
alias kgy='kubectl get -o yaml'
alias kgpo='kubectl get pods'

# Container commands
#
alias cexec='"$CONTAINER_RUNTIME" run \
                --rm \
                --interactive \
                --tty \
                --pull always \
                --entrypoint /bin/sh -v "$(pwd)":/workspace'

# WPScan
#
alias wpscan='"$CONTAINER_RUNTIME" run \
                --rm \
                --interactive \
                --tty \
                --pull always \
                --log-level fatal \
                --clear-cache \
                --update \
                --api-token "$WPSCAN_API_TOKEN" \
                --enumerate vp,vt,tt,cb,dbe,u,m \
                --random-user-agent \
                --url \
                wpscanteam/wpscan'

# Pressman
#
alias pressman='"$CONTAINER_RUNTIME" run \
                --rm \
                --interactive \
                --tty \
                --pull always \
                -v "$(pwd)":/workspace \
                docker.io/leventogut/pressman'

# Kubernetes Toolbox
#
alias toolbox='"$CONTAINER_RUNTIME" run \
                --rm \
                --interactive \
                --tty \
                --pull always \
                --name toolbox \
                --hostname toolbox \
                --network=host \
                --add-host=host.docker.internal:host-gateway \
                -v "$HOME/.ssh:/root/.ssh" \
                -v "$HOME/.kube:/root/.kube" \
                -v "$HOME/.config/gcloud":/root/.config/gcloud \
                -v "$HOME/.aws:/root/.aws" \
                -v "$HOME/.azure:/root/.azure" \
                -v "$(pwd):/workspace" \
                docker.io/leventogut/toolbox:latest'
